name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-android:
    name: Build, Approve & Distribute (Prod)
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'
          channel: 'stable'
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/upload-keystore.jks

      - name: Write key.properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" > android/key.properties

      - name: Build and distribute prod build
        working-directory: android
        run: bundle exec fastlane distribute_prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROD_APP_ID: ${{ secrets.FIREBASE_PROD_APP_ID }}